services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883" # mqtt listener
      - "9001:9001" # ws listener
    volumes:
      - ./mosquitto-config:/mosquitto/config:rw
#      - ./mosquitto/data:/mosquitto/data:rw
#      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped
    privileged: true
  mqttx:
    image: emqx/mqttx-web
    container_name: mqttx
    restart: unless-stopped
    ports:
      - "8089:80"
