// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using btserver.Data;

#nullable disable

namespace btserver.Data.Migrations
{
    [DbContext(typeof(BtDbContext))]
    partial class BtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("btserver.Zone.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedArtifactIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("btserver.Zone.StaticZone", b =>
                {
                    b.HasBaseType("btserver.Zone.Zone");

                    b.Property<string>("MachineIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("StaticZones");
                });

            modelBuilder.Entity("btserver.Zone.SubnetZone", b =>
                {
                    b.HasBaseType("btserver.Zone.Zone");

                    b.Property<string>("Subnet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("SubnetZones");
                });
#pragma warning restore 612, 618
        }
    }
}
